# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Solver.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.result_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.result_text.setGeometry(QtCore.QRect(10, 40, 400, 300))
        self.result_text.setReadOnly(True)
        self.result_text.setObjectName("result_text")
        self.rule_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.rule_text.setGeometry(QtCore.QRect(420, 40, 300, 300))
        self.rule_text.setObjectName("rule_text")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(10, 10, 400, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.result_label.setFont(font)
        self.result_label.setScaledContents(False)
        self.result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.result_label.setObjectName("result_label")
        self.rule_label = QtWidgets.QLabel(self.centralwidget)
        self.rule_label.setGeometry(QtCore.QRect(420, 10, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rule_label.setFont(font)
        self.rule_label.setTextFormat(QtCore.Qt.PlainText)
        self.rule_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rule_label.setObjectName("rule_label")
        self.category_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.category_text.setGeometry(QtCore.QRect(420, 410, 300, 100))
        self.category_text.setPlainText("")
        self.category_text.setObjectName("category_text")
        self.category_label = QtWidgets.QLabel(self.centralwidget)
        self.category_label.setGeometry(QtCore.QRect(420, 380, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.category_label.setFont(font)
        self.category_label.setAlignment(QtCore.Qt.AlignCenter)
        self.category_label.setObjectName("category_label")
        self.output_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.output_text.setGeometry(QtCore.QRect(10, 410, 400, 100))
        self.output_text.setReadOnly(True)
        self.output_text.setObjectName("output_text")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(10, 380, 400, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output_label.setFont(font)
        self.output_label.setAlignment(QtCore.Qt.AlignCenter)
        self.output_label.setObjectName("output_label")
        self.solve_button = QtWidgets.QPushButton(self.centralwidget)
        self.solve_button.setGeometry(QtCore.QRect(10, 520, 100, 30))
        self.solve_button.setObjectName("solve_button")
        self.clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(130, 520, 100, 30))
        self.clear_button.setObjectName("clear_button")
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(250, 520, 100, 30))
        self.reset_button.setObjectName("reset_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 730, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTutorial = QtWidgets.QAction(MainWindow)
        self.actionTutorial.setObjectName("actionTutorial")
        self.menuFile.addAction(self.actionTutorial)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.result_label.setText(_translate("MainWindow", "Result"))
        self.rule_label.setText(_translate("MainWindow", "Rules"))
        self.category_label.setText(_translate("MainWindow", "Categories"))
        self.output_label.setText(_translate("MainWindow", "Output"))
        self.solve_button.setText(_translate("MainWindow", "Solve"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))
        self.reset_button.setText(_translate("MainWindow", "Reset"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionTutorial.setText(_translate("MainWindow", "Tutorial"))
